export const Card = [
  {
    id: 1,
    image: "/card/cardImage1.png",
    imageText: "Medical",
    title: "Medical Treatment for Sarah&apos;s Cancer Recovery",
    icon1: "/",
    name: "Sarah Johnson",
    Icon2: "/",
    time: "23 days",
    timeText: "remaining",
    buttonText: "Donate now",
  },
  {
    id: 2,
    image: "/card/cardImage2.png",
    imageText: "Emergency",
    title: "Emergency Refief For Food victims",
    icon1: "/",
    name: "Disaster Relief Network",
    Icon2: "/",
    time: "8 days",
    timeText: "remaining",
    buttonText: "Donate now",
  },
  {
    id: 3,
    image: "/card/cardImage3.png",
    imageText: "Eduation",
    title: "Education fund for Underprivileged Children",
    icon1: "/",
    name: "Hope Foundation",
    Icon2: "/",
    time: "15 days",
    timeText: "remaining",
    buttonText: "Donate now",
  },
  {
    id: 4,
    image: "/card/cardImage4.png",
    imageText: "Amenities",
    title: "Emergency Relief For Food victims",
    icon1: "/",
    name: "Disaster Relief Network",
    Icon2: "/",
    time: "8 days",
    timeText: "remaining",
    buttonText: "Donate now",
  },
  {
    id: 5,
    image: "/card/cardImage5.png",
    imageText: "Green life",
    title: "Emergency Refief For Food victims",
    icon1: "/",
    name: "Disaster Relief Network",
    Icon2: "/",
    time: "8 days",
    timeText: "remaining",
    buttonText: "Donate now",
  },
  {
    id: 6,
    image: "/card/cardImage6.png",
    imageText: "Nature",
    title: "Emergency Refief For Food victims",
    icon1: "/",
    name: "Disaster Relief Network",
    Icon2: "/",
    time: "8 days",
    timeText: "remaining",
    buttonText: "Donate now",
  },
];
