import { FaHourglassHalf } from "react-icons/fa";
import { CiUser } from "react-icons/ci";

export const Card = [
  {
    id: 1,
    image: "/card/cardImage1.png",
    imageText: "Medical",
    title: "Medical Treatment for Sarah's Cancer Recovery",
    icon1: <CiUser />,
    name: "Sarah Johnson",
    Icon2: <FaHourglassHalf />,
    time: "23 days",
    timeText: "remaining",
    buttonText: "Donate now",
  },
  {
    id: 2,
    image: "/card/cardImage2.png",
    imageText: "Emergency",
    title: "Emergency Relief For Food victims",
    icon1: <CiUser />,
    name: "Disaster Relief Network",
    Icon2: <FaHourglassHalf />,
    time: "8 days",
    timeText: "remaining",
    buttonText: "Donate now",
  },
  {
    id: 3,
    image: "/card/cardImage3.png",
    imageText: "Eduation",
    title: "Education fund for Underprivileged Children",
    icon1: <CiUser />,
    name: "Hope Foundation",
    Icon2: <FaHourglassHalf />,
    time: "15 days",
    timeText: "remaining",
    buttonText: "Donate now",
  },
  {
    id: 4,
    image: "/card/cardImage4.png",
    imageText: "Amenities",
    title: "Clean Water Project for Remote Village",
    icon1: <CiUser />,
    name: "Disaster Relief Network",
    Icon2: <FaHourglassHalf />,
    time: "8 days",
    timeText: "remaining",
    buttonText: "Donate now",
  },
  {
    id: 5,
    image: "/card/cardImage5.png",
    imageText: "Green life",
    title: "Green Ecosystem Life Recovery After Fire",
    icon1: <CiUser />,
    name: "Disaster Relief Network",
    Icon2: <FaHourglassHalf />,
    time: "8 days",
    timeText: "remaining",
    buttonText: "Donate now",
  },
  {
    id: 6,
    image: "/card/cardImage6.png",
    imageText: "Nature",
    title: "Community Environment Clean up",
    icon1: <CiUser />,
    name: "Disaster Relief Network",
    Icon2: <FaHourglassHalf />,
    time: "8 days",
    timeText: "remaining",
    buttonText: "Donate now",
  },
];
